"""
Backend Feature: Response Classification

INPUT:
--> String 1: Audio Transcript
--> String 2: Job Description
--> String 3: Question Asked


OUTPUT:
--> Sentiment Analysis: Confident vs. Not Confident
--> Generative AI: User Response vs. Job Description
"""
import cohere
from cohere.responses.classify import Example

training_data = [

    # CONFIDENT TRAINING DATA
    Example("I am currently pursuing a degree in Computer Science, where my passion for coding and problem-solving thrives. My academic journey has exposed me to various programming languages and algorithms, enhancing my analytical skills. I have engaged in exciting projects, like developing a mobile app for efficient data management. Beyond coursework, I interned at a tech firm, where I collaborated on innovative software solutions. My goal is to contribute to groundbreaking advancements in the tech industry, combining my technical prowess with a creative approach.", "Confident"),
    Example("As an engineering student, I immerse myself in the fascinating realm of problem-solving and innovation. My coursework spans diverse disciplines, from mechanical to electrical engineering, fostering a holistic understanding of the field. I actively participate in hands-on projects, such as designing a sustainable energy prototype. Interning with an engineering consultancy sharpened my practical skills, where I contributed to real-world projects. With a keen interest in sustainable solutions, I aim to apply my knowledge to address contemporary challenges in the engineering domain.", "Confident"),
    Example("I am currently pursuing a degree in Education, driven by my passion for shaping young minds and fostering a love for learning. My coursework delves into pedagogy, child psychology, and instructional strategies. Engaging in classroom observations and student-teaching experiences has honed my ability to create inclusive and effective learning environments. I am dedicated to making a positive impact on students' lives, inspiring them to reach their full potential. My goal is to contribute meaningfully to the field of education and instill a lifelong love for learning in my students.", "Confident"),
    Example("In the realm of mathematics, I am passionate about unraveling the beauty of numbers and patterns. My academic journey involves in-depth studies of calculus, algebra, and statistical analysis. Engaging in research projects, like exploring mathematical modeling, has deepened my appreciation for the subject's real-world applications. I thrive on solving complex problems and am particularly fascinated by the intersection of mathematics and technology. With a commitment to continuous learning, I aspire to contribute valuable insights to the ever-evolving field of mathematics.", "Confident"),
    Example("As a psychology major, my academic journey revolves around understanding the complexities of the human mind and behavior. My coursework covers a broad spectrum, from cognitive psychology to behavioral neuroscience. Engaging in research projects, such as studying the impact of stress on cognitive functions, has honed my analytical skills. Interning at a counseling center provided valuable practical experience in supporting individuals facing mental health challenges. My passion lies in contributing to the well-being of individuals and promoting mental health awareness.", "Confident"),
    Example("In the dynamic field of communications, I am dedicated to mastering the art of effective expression and media literacy. My coursework spans journalism, public relations, and digital media. I have actively contributed to campus publications, refining my writing and editing skills. Interning with a media agency allowed me to work on diverse projects, from social media campaigns to press releases. I am excited about the evolving landscape of communications and aspire to leverage my skills to convey impactful messages in the digital age.", "Confident"),
    Example("In the realm of construction management, I am navigating the intricate balance between design, planning, and execution. My coursework encompasses project management, structural analysis, and sustainable construction practices. Engaging in hands-on projects, such as overseeing a small-scale construction site, has honed my practical skills. Interning with a construction firm provided valuable insights into real-world challenges and effective problem-solving. I am passionate about contributing to the built environment with sustainable and efficient construction practices.", "Confident"),
    Example("As an economics major, my academic journey revolves around unraveling the intricacies of economic systems and their impact on society. My coursework spans microeconomics, macroeconomics, and econometrics. Engaging in research projects, such as analyzing market trends and forecasting economic indicators, has deepened my analytical skills. Interning with an economic research institute provided practical experience in data analysis and policy research. I am driven by a curiosity to understand the forces shaping global economies and aspire to contribute insights to informed decision-making.", "Confident"),
    Example("In the dynamic field of information science, I am exploring the convergence of technology, data, and user experience. My coursework spans database management, information retrieval, and user interface design. Engaging in projects, such as developing a user-friendly information system, has enhanced my technical and problem-solving skills. Interning with a tech startup allowed me to apply theoretical knowledge to real-world scenarios. I am passionate about leveraging information science to enhance accessibility and usability in the digital landscape.", "Confident"),
    Example("As an architecture student, I am immersed in the creative and technical aspects of designing spaces that harmonize with the environment. My coursework delves into architectural theory, design principles, and sustainable practices. Engaging in studio projects, such as conceptualizing innovative building designs, has honed my creativity and spatial awareness. Interning with an architectural firm provided practical insights into the collaborative and dynamic nature of the field. I am driven by a commitment to creating aesthetically pleasing and functional spaces that enrich communities.", "Confident"),
    Example("In the realm of art, my academic journey is a canvas for self-expression and creative exploration. My coursework spans various mediums, from painting to digital art, allowing me to cultivate a diverse skill set. Engaging in gallery exhibitions and collaborative projects has enriched my understanding of the artistic process. I am passionate about conveying meaningful narratives through visual expressions and aspire to contribute to the cultural tapestry through my artistic endeavors.", "Confident"),
    Example("As a human resources major, I am dedicated to fostering a positive and productive work environment through effective people management. My coursework covers organizational behavior, talent acquisition, and employee relations. Engaging in practical projects, such as developing HR policies and conducting employee training, has honed my interpersonal and leadership skills. Interning with a multinational corporation allowed me to apply theoretical knowledge to real-world HR challenges. I am driven by a commitment to building strong and inclusive workplace cultures.", "Confident"),
    Example("In the vast landscape of humanities, I am on a quest to understand the rich tapestry of human history, culture, and expression. My coursework spans literature, philosophy, and cultural studies, fostering a nuanced perspective on the human experience. Engaging in research projects, such as exploring the impact of historical events on literature, has deepened my analytical skills. I am passionate about fostering empathy and critical thinking through the humanities, contributing to a more informed and interconnected society.", "Confident"),
    Example("In the dynamic field of journalism, I am dedicated to uncovering and conveying compelling stories that shape our understanding of the world. My coursework spans investigative journalism, multimedia storytelling, and ethics. Actively contributing to campus publications and covering events has honed my writing and reporting skills. Interning with a news organization provided valuable insights into the fast-paced and ever-evolving nature of journalism. I am committed to upholding the principles of truth and transparency in my pursuit of impactful storytelling.", "Confident"),
    Example("As a social sciences major, I am immersed in the study of human societies and the intricate dynamics that shape them. My coursework spans sociology, anthropology, and political science, fostering a holistic understanding of societal structures. Engaging in research projects, such as studying the impact of cultural diversity on community dynamics, has deepened my analytical skills. I am passionate about contributing to social change through informed discourse and evidence-based approaches.", "Confident"),
    Example("In the realm of accounting, I am dedicated to unraveling the language of business and financial management. My coursework covers financial accounting, auditing, and taxation. Engaging in practical projects, such as preparing financial statements and conducting audits, has honed my attention to detail and analytical skills. Interning with an accounting firm provided real-world experience in navigating complex financial transactions. I am committed to upholding the principles of accuracy and transparency in financial reporting.", "Confident"),
    Example("As an agriculture major, I am deeply rooted in the study of sustainable farming practices and the global food system. My coursework spans agronomy, crop science, and agricultural economics. Engaging in hands-on projects, such as managing a community garden, has honed my practical skills. Interning with a sustainable agriculture initiative allowed me to apply theoretical knowledge to real-world challenges. I am passionate about contributing to food security and environmentally conscious agriculture practices.", "Confident"),
    Example("In the realm of biology, I am dedicated to unraveling the mysteries of life and the intricate processes that govern living organisms. My coursework spans genetics, ecology, and molecular biology. Engaging in research projects, such as studying the impact of environmental factors on species diversity, has deepened my analytical skills. I am passionate about contributing to scientific advancements and understanding the interconnectedness of ecosystems. My goal is to make meaningful contributions to the field of biology through research and exploration.", "Confident"),
    Example("As a business major, I am dedicated to navigating the complexities of the corporate world and fostering sustainable growth. My coursework covers marketing, finance, and strategic management. Engaging in practical projects, such as developing business plans and conducting market analyses, has honed my strategic thinking and analytical skills. Interning with a multinational corporation provided valuable insights into global business operations. I am committed to leveraging my business acumen to drive innovation and contribute to the success of organizations.", "Confident"),
    Example("In the interdisciplinary field of biomedical engineering, I am dedicated to merging the principles of engineering with the intricacies of healthcare. My coursework spans biomechanics, medical imaging, and bioinformatics. Engaging in research projects, such as developing wearable health monitoring devices, has honed my technical and problem-solving skills. Interning with a medical device company allowed me to apply theoretical knowledge to real-world medical challenges. I am passionate about advancing healthcare through innovative engineering solutions.", "Confident"),
    Example("In the realm of health professions, I am dedicated to the well-being of individuals and communities through healthcare delivery and promotion. My coursework spans anatomy, physiology, and public health. Engaging in clinical experiences and community health projects has honed my practical skills. Interning at a healthcare facility provided valuable insights into patient care and healthcare administration. I am driven by a commitment to making a positive impact on people's lives and contributing to the advancement of healthcare.", "Confident"),
    Example("In the dynamic field of civil engineering, I am dedicated to shaping the built environment and infrastructure that underpins modern society. My coursework spans structural engineering, transportation planning, and environmental engineering. Engaging in projects, such as designing sustainable urban infrastructure, has honed my technical and problem-solving skills. Interning with a civil engineering firm provided practical experience in navigating complex projects. I am passionate about contributing to the development of resilient and sustainable communities.", "Confident"),
    Example("As a human services major, I am dedicated to advocating for and supporting individuals and communities in need. My coursework spans social work, counseling, and community development. Engaging in hands-on projects, such as working with local nonprofits, has honed my interpersonal and advocacy skills. Interning with a social services agency provided valuable insights into the challenges faced by marginalized populations. I am committed to making a positive impact through compassionate and informed service delivery.", "Confident"),
    Example("In the thrilling field of aeronautics, I am dedicated to unraveling the complexities of flight and aerospace technology. My coursework spans aerodynamics, avionics, and aircraft design. Engaging in hands-on projects, such as designing and testing a small-scale aircraft, has honed my technical and problem-solving skills. Interning with an aerospace company provided practical insights into the cutting-edge developments in the field. I am passionate about contributing to the advancement of aeronautical engineering and pushing the boundaries of human exploration.", "Confident"),
    Example("In my most recent project, I collaborated with a team to develop a web-based inventory management system using Java and Spring framework. We faced challenges in optimizing database queries for efficiency, ensuring data security, and implementing a user-friendly interface. Through effective communication and problem-solving, we successfully delivered the project on time, exceeding client expectations.", "Confident"),
    Example("One project I worked on during my studies involved creating a mobile application for real-time language translation. Utilizing Python and TensorFlow, we overcame challenges related to natural language processing and integration of the translation engine. We adopted an agile approach, facilitating quick adaptations to evolving requirements. The project received positive feedback for its accuracy and speed in language translation.", "Confident"),
    Example("During my internship, I contributed to a data analytics project aimed at optimizing supply chain operations. Using R and SQL, we processed large datasets to identify bottlenecks and recommend improvements. Challenges included handling diverse data sources and ensuring the accuracy of predictive models. Through close collaboration with cross-functional teams, we implemented solutions that led to a significant reduction in operational costs.", "Confident"),
    Example("In a cybersecurity project, I led the development of a threat detection system using machine learning algorithms. Challenges included refining the model for false positive reduction and integrating it into existing security infrastructure. Through iterative testing and feedback, we achieved a high level of accuracy in identifying potential threats. The success of the project highlighted my ability to lead technical initiatives and collaborate effectively within a team.", "Confident"),
    Example("I spearheaded a software engineering project focusing on creating an e-learning platform. Using React for the frontend and Node.js for the backend, we faced challenges in ensuring seamless user experience and real-time updates. Implementing WebSockets and optimizing server-client communication were critical aspects. Through meticulous testing and continuous integration, we delivered a robust platform that supported a dynamic learning environment.", "Confident"),
    Example("My involvement in a computer vision project showcased my proficiency in image recognition using deep learning techniques. We used TensorFlow and Python to develop a system that identified objects in real-time. Challenges included model optimization for resource-constrained environments and addressing variability in image quality. The project's success underscored my ability to apply theoretical knowledge to practical, real-world applications.", "Confident"),
    Example("I participated in a software development project focused on automating business processes using a microservices architecture. Challenges included coordinating communication between microservices and ensuring fault tolerance. Adopting Docker and Kubernetes addressed deployment challenges, and implementing API gateways streamlined interactions. The project's success highlighted my competence in designing scalable and resilient software solutions.", "Confident"),
    Example("As part of a mobile app development project, I utilized Flutter to create a cross-platform application. Challenges involved optimizing the app for various screen sizes and addressing compatibility issues. Through rigorous testing and user feedback, we refined the user interface and enhanced overall user experience. The project's positive reception emphasized my proficiency in mobile app development and UI/UX design.", "Confident"),
    Example("In a collaborative research project, I applied machine learning algorithms to analyze healthcare data for predictive modeling. Challenges included data preprocessing, feature selection, and ensuring model interpretability. Through interdisciplinary collaboration, we addressed these challenges and developed a predictive model that contributed valuable insights to the healthcare field.", "Confident"),
    Example("During a hackathon, I led a team to develop a blockchain-based voting system. Challenges included ensuring the security and transparency of the voting process. Leveraging smart contracts and cryptography, we created a system that provided a secure and verifiable voting mechanism. The project's success demonstrated my ability to innovate and apply emerging technologies to address real-world challenges.", "Confident"),

    # NOT CONFIDENT TRAINING DATA
    Example("Um, so like, I is currently pursuing a degree in Compter Science, where my passion for coding and problem-solving, ummsss, thrives. My academic journey has exposed me to various programming languages and algorithms, enhancing my analytical skills, ummsss. I have engaged in, like, exciting projects, like developing a mobile app for, ummsss, efficient data management. Beyond coursework, I interned at, like, a tech firm, where I collaborated on innovative software solutions. My goal is to, ummsss, contribute to groundbreaking advancements in the tech industry, combining my technical prowess with, ummsss, a creative approach.", "Not Confident"),
    Example("As an engineering student, ummsss, I immerse myself in the fascinating realm of problem-solving and, like, innovation. My coursework spans diverse disciplines, from, ummsss, mechanical to electrical engineering, fostering a holistic understanding of the field. I actively participate in hands-on projects, such as, ummsss, designing a sustainable energy prototype. Interning with an, like, engineering consultancy sharpened my practical skills, where I contributed to real-world projects, ummsss. With a keen interest in sustainable solutions, I aim to apply my knowledge to address, ummsss, contemporary challenges in the engineering domain.", "Not Confident"),
    Example("I is currently pursuing a degree in Education, driven by my passion for shaping, ummsss, young minds and fostering a love for learning. My coursework delves into pedagogy, child psychology, and, ummsss, instructional strategies. Engaging in classroom observations and student-teaching experiences has honed my ability to create, ummsss, inclusive and effective learning environments. I am dedicated to making a positive impact on, ummsss, students' lives, inspiring them to reach their full potential. My goal is to contribute meaningfully to the, ummsss, field of education and instill a lifelong love for learning in my students.", "Not Confident"),
    Example("In the realm of mathematics, ummsss, I am passionate about unraveling the beauty of numbers and patterns. My academic journey involves in-depth studies of calculus, algebra, and, ummsss, statistical analysis. Engaging in research projects, like, exploring mathematical modeling, has deepened my appreciation for the subject's real-world applications, ummsss. I thrive on, ummsss, solving complex problems and am particularly fascinated by the intersection of mathematics and technology. With a commitment to, like, continuous learning, I aspire to contribute valuable insights to the ever-evolving field of mathematics.", "Not Confident"),
    Example("As a psychology major, ummsss, my academic journey revolves around understanding the complexities of the human mind and behavior, ummsss. My coursework covers a broad spectrum, from cognitive psychology to, like, behavioral neuroscience. Engaging in research projects, such as, ummsss, studying the impact of stress on cognitive functions, has honed my analytical skills. Interning at, like, a counseling center provided valuable practical experience in supporting individuals facing mental health challenges, ummsss. My passion lies in contributing to, like, the well-being of individuals and promoting mental health awareness.", "Not Confident"),
    Example("In the dynamic field of communications, ummsss, I am dedicated to mastering the art of effective expression and, like, media literacy. My coursework spans journalism, public relations, and digital media. I have, ummsss, actively contributed to campus publications, refining my writing and editing skills. Interning with a, like, media agency allowed me to work on diverse projects, from social media campaigns to, ummsss, press releases. I am excited about, like, the evolving landscape of communications and aspire to leverage my skills to convey impactful messages in the digital age.", "Not Confident"),
    Example("In the realm of construction management, ummsss, I am navigating the intricate balance between design, planning, and, like, execution. My coursework encompasses project management, structural analysis, and, ummsss, sustainable construction practices. Engaging in hands-on projects, such as, ummsss, overseeing a small-scale construction site, has honed my practical skills. Interning with a construction firm provided valuable insights into, like, real-world challenges and effective problem-solving. I am passionate about contributing to the, ummsss, built environment with sustainable and efficient construction practices.", "Not Confident"),
    Example("As an economics major, ummsss, my academic journey revolves around unraveling the intricacies of economic systems and, like, their impact on society. My coursework spans microeconomics, macroeconomics, and, ummsss, econometrics. Engaging in research projects, like, analyzing market trends and forecasting economic indicators, has deepened my analytical skills, ummsss. Interning with an economic research institute provided, like, practical experience in data analysis and policy research. I am driven by a curiosity to, ummsss, understand the forces shaping global economies and aspire to contribute insights to informed decision-making.", "Not Confident"),
    Example("In the dynamic field of information science, ummsss, I is exploring the convergence of technology, data, and, like, user experience. My coursework spans database management, information retrieval, and, ummsss, user interface design. Engaging in projects, like, developing a user-friendly information system, has enhanced my technical and, ummsss, problem-solving skills. Interning with a tech startup allowed me to apply theoretical knowledge to, like, real-world scenarios. I am passionate about leveraging information science to, ummsss, enhance accessibility and usability in the digital landscape.", "Not Confident"),
    Example("As an architecture student, ummsss, I am immersed in the creative and technical aspects of designing spaces that, like, harmonize with the environment. My coursework delves into architectural theory, design principles, and, ummsss, sustainable practices. Engaging in studio projects, such as, like, conceptualizing innovative building designs, has honed my creativity and spatial awareness, ummsss. Interning with an architectural firm provided, like, practical insights into the collaborative and dynamic nature of the field. I am driven by a commitment to, ummsss, creating aesthetically pleasing and functional spaces that enrich communities.", "Not Confident"),
    Example("In the realm of art, ummsss, my academic journey is a canvas for, like, self-expression and creative exploration. My coursework spans various mediums, from painting to, ummsss, digital art, allowing me to cultivate a diverse skill set. Engaging in gallery exhibitions and, like, collaborative projects has enriched my understanding of the artistic process. I am passionate about conveying, ummsss, meaningful narratives through visual expressions and aspire to contribute to the cultural tapestry through, like, my artistic endeavors.", "Not Confident"),
    Example("As a human resources major, ummsss, I am dedicated to fostering a positive and productive work environment through effective people management, ummsss. My coursework covers organizational behavior, talent acquisition, and, like, employee relations. Engaging in practical projects, such as, ummsss, developing HR policies and conducting employee training, has honed my interpersonal and leadership skills. Interning with a multinational corporation allowed me to, like, apply theoretical knowledge to real-world HR challenges. I am driven by a commitment to building, ummsss, strong and inclusive workplace cultures.", "Not Confident"),
    Example("In the vast landscape of, like, humanities, ummsss, I am on a quest to understand the rich tapestry of human history, culture, and expression. My coursework spans literature, philosophy, and, ummsss, cultural studies, fostering a nuanced perspective on the human experience. Engaging in research projects, like, exploring the impact of historical events on, ummsss, literature, has deepened my analytical skills. I am passionate about fostering empathy and critical thinking, like, through the humanities, contributing to a more informed and interconnected society.", "Not Confident"),
    Example("In the dynamic field of journalism, ummsss, I am dedicated to uncovering and conveying compelling stories that shape our understanding of the world, ummsss. My coursework spans investigative journalism, multimedia storytelling, and, like, ethics. Actively contributing to campus publications and covering events has, ummsss, honed my writing and reporting skills. Interning with a news organization provided, like, valuable insights into the fast-paced and ever-evolving nature of journalism. I am committed to, ummsss, upholding the principles of truth and transparency in my pursuit of impactful storytelling.", "Not Confident"),
    Example("As a social sciences major, ummsss, I am immersed in the study of human societies and the, like, intricate dynamics that shape them. My coursework spans sociology, anthropology, and, ummsss, political science, fostering a holistic understanding of societal structures. Engaging in research projects, like, studying the impact of cultural diversity on, ummsss, community dynamics, has deepened my analytical skills. I am passionate about contributing to, like, social change through informed discourse and evidence-based approaches.", "Not Confident"),
    Example("In the realm of accounting, ummsss, I am dedicated to unraveling the language of, like, business and financial management. My coursework covers financial accounting, auditing, and, ummsss, taxation. Engaging in practical projects, such as, like, preparing financial statements and conducting audits, has honed my attention to detail and analytical, ummsss, skills. Interning with an accounting firm provided, like, real-world experience in navigating complex financial transactions. I am committed to upholding the, ummsss, principles of accuracy and transparency in financial reporting.", "Not Confident"),
    Example("As an agriculture major, ummsss, I am deeply rooted in the study of, like, sustainable farming practices and the global food system. My coursework spans agronomy, crop science, and, ummsss, agricultural economics. Engaging in hands-on projects, such as, like, managing a community garden, has honed my practical skills. Interning with a, ummsss, sustainable agriculture initiative allowed me to apply theoretical knowledge to real-world, like, challenges. I am passionate about contributing to food security and environmentally conscious, ummsss, agriculture practices.", "Not Confident"),
    Example("In the realm of biology, ummsss, I am dedicated to unraveling the mysteries of life and the, like, intricate processes that govern living organisms. My coursework spans genetics, ecology, and, ummsss, molecular biology. Engaging in research projects, like, studying the impact of environmental factors on species diversity, has deepened my analytical skills, ummsss. I am passionate about contributing to, like, scientific advancements and understanding the interconnectedness of ecosystems. My goal is to, ummsss, make meaningful contributions to the field of biology through research and, like, exploration.", "Not Confident"),
    Example("As a business major, ummsss, I am dedicated to navigating the complexities of the corporate world and, like, fostering sustainable growth. My coursework covers marketing, finance, and, ummsss, strategic management. Engaging in practical projects, like, developing business plans and conducting market analyses, has honed my strategic thinking and, ummsss, analytical skills. Interning with a multinational corporation provided valuable insights into global business operations, ummsss. I am committed to leveraging my business acumen to, like, drive innovation and contribute to the success of organizations.", "Not Confident"),
    Example("In the interdisciplinary field of biomedical engineering, ummsss, I am dedicated to merging the principles of, like, engineering with the intricacies of healthcare. My coursework spans biomechanics, medical imaging, and, ummsss, bioinformatics. Engaging in research projects, like, developing wearable health monitoring devices, has honed my technical and, ummsss, problem-solving skills. Interning with a medical device company allowed me to apply theoretical knowledge to, like, real-world medical challenges. I am passionate about advancing healthcare through, ummsss, innovative engineering solutions.", "Not Confident"),
    Example("In the realm of health professions, ummsss, I am dedicated to the well-being of individuals and, like, communities through healthcare delivery and promotion. My coursework spans anatomy, physiology, and, ummsss, public health. Engaging in clinical experiences and community health projects has, like, honed my practical skills. Interning at a healthcare facility provided valuable insights into patient care and, ummsss, healthcare administration. I am driven by a commitment to making a positive impact on people's lives and contributing to the, like, advancement of healthcare.", "Not Confident"),
    Example("In the dynamic field of civil engineering, ummsss, I am dedicated to shaping the built environment and, like, infrastructure that underpins modern society. My coursework spans structural engineering, transportation planning, and, ummsss, environmental engineering. Engaging in projects, like, designing sustainable urban infrastructure, has honed my technical and, ummsss, problem-solving skills. Interning with a civil engineering firm provided practical experience in, like, navigating complex projects. I am passionate about contributing to the development of resilient and, ummsss, sustainable communities.", "Not Confident"),
    Example("As a human services major, ummsss, I am dedicated to advocating for and, like, supporting individuals and communities in need. My coursework spans social work, counseling, and, ummsss, community development. Engaging in hands-on projects, such as, like, working with local nonprofits, has honed my interpersonal and advocacy skills. Interning with a social services, ummsss, agency provided valuable insights into the challenges faced by marginalized populations. I am committed to making, like, a positive impact through compassionate and informed service delivery.", "Not Confident"),
    Example("In the thrilling field of aeronautics, ummsss, I am dedicated to unraveling the complexities of, like, flight and aerospace technology. My coursework spans aerodynamics, avionics, and, ummsss, aircraft design. Engaging in hands-on projects, like, designing and testing a small-scale aircraft, has honed my technical and, ummsss, problem-solving skills. Interning with an aerospace company provided, like, practical insights into the cutting-edge developments in the field. I am passionate about, ummsss, contributing to the advancement of aeronautical engineering and pushing the boundaries of human, like, exploration.", "Not Confident"),
    Example("Um, in my, like, most recent project, I collaborated with a team to, um, develop a web-based inventory management system using Java and the, like, Spring framework. We, um, faced challenges in, like, optimizing database queries for efficiency, ensuring data security, and, um, implementing a user-friendly interface. Through, um, effective communication and, like, problem-solving, we successfully delivered the project on time, exceeding, like, client expectations.", "Not Confident"),
    Example("Like, one project I worked on during my studies involved creating a mobile application for, um, real-time language translation. Utilizing Python and, um, TensorFlow, we, like, overcame challenges related to natural language processing and, um, integration of the translation engine. We, um, adopted an agile approach, facilitating quick, um, adaptations to evolving requirements. The project received, like, positive feedback for its accuracy and, um, speed in language translation.", "Not Confident"),
    Example("During my internship, I contributed to a data analytics project aimed at, um, optimizing supply chain operations. Using R and, um, SQL, we processed, like, large datasets to identify bottlenecks and, um, recommend improvements. Challenges included, um, handling diverse data sources and ensuring the, like, accuracy of predictive models. Through, um, close collaboration with cross-functional teams, we implemented solutions that, um, led to a significant reduction in operational costs.", "Not Confident"),
    Example("In a cybersecurity project, I, um, led the development of a threat detection system using, um, machine learning algorithms. Challenges included, like, refining the model for false positive reduction and, um, integrating it into existing security infrastructure. Through, um, iterative testing and, like, feedback, we achieved a high level of accuracy in, like, identifying potential threats. The success of the project highlighted my ability to lead, um, technical initiatives and, um, collaborate effectively within a team.", "Not Confident"),
    Example("I spearheaded, like, a software engineering project focusing on, um, creating an e-learning platform. Using React for the, like, frontend and Node.js for the backend, we faced challenges in, um, ensuring seamless user experience and, um, real-time updates. Implementing WebSockets and, um, optimizing server-client communication were critical aspects. Through, um, meticulous testing and continuous integration, we delivered a, like, robust platform that supported a dynamic learning environment.", "Not Confident"),
    Example("My involvement in a, like, computer vision project showcased my proficiency in, um, image recognition using deep learning techniques. We used TensorFlow and Python to, um, develop a system that identified objects in real-time. Challenges included, like, model optimization for resource-constrained environments and, um, addressing variability in image quality. The project's success underscored my ability to, um, apply theoretical knowledge to, um, practical, real-world applications.", "Not Confident"),
    Example("I participated in, like, a software development project focused on, um, automating business processes using a, um, microservices architecture. Challenges included coordinating, um, communication between microservices and ensuring, um, fault tolerance. Adopting Docker and Kubernetes addressed, like, deployment challenges, and implementing API gateways streamlined, um, interactions. The project's success highlighted my, um, competence in designing scalable and, like, resilient software solutions.", "Not Confident"),
    Example("As part of, um, a mobile app development project, I utilized Flutter to, like, create a cross-platform application. Challenges involved, um, optimizing the app for, like, various screen sizes and addressing, um, compatibility issues. Through, um, rigorous testing and, like, user feedback, we refined the user interface and, um, enhanced overall user experience. The project's positive reception emphasized my, um, proficiency in mobile app development and, um, UI/UX design.", "Not Confident"),
    Example("In a collaborative, like, research project, I applied machine learning algorithms to, um, analyze healthcare data for predictive modeling. Challenges included, um, data preprocessing, feature selection, and, like, ensuring model interpretability. Through, um, interdisciplinary collaboration, we addressed these challenges and, um, developed a predictive model that contributed, um, valuable insights to the healthcare field.", "Not Confident"),
    Example("During, um, a hackathon, I led a team to, like, develop a blockchain-based voting system. Challenges included, um, ensuring the security and transparency of the, like, voting process. Leveraging smart contracts and, um, cryptography, we created a system that provided a secure and, um, verifiable voting mechanism. The project's success, um, demonstrated my ability to, like, innovate and apply emerging technologies to, um, address real-world challenges.", "Not Confident"),

]

class CohereTool:

	def __init__(self, audio_transcript, job_description, question):
		self.co = cohere.Client('i531EpIrFjjxiK01Qw8MyhfU5VIMl4CBAPoEWOI7')
		self.audio_transcript = audio_transcript
		self.job_description = job_description
		self.question = question

	def get_sentiment_analysis(self) -> (str, float):
		"""
		Return whether the response is confident, along with a confidence score.
		--> Ex: ("Confident", 0.93217)
		"""
		response = self.co.classify(
		  inputs=[self.audio_transcript],
		  examples=training_data,
		)
		return (response[0].prediction, response[0].confidence)

	def get_response_feedback(self) -> str:
		"""Return a string with a pros/cons list on the response, while taking the job description and question into account."""
		response = self.co.chat(
		  chat_history=[
		    {"role": "USER", "message": "I am going to give you a job description, a question I was asked and my response to the question. I want you to give me a list of pros and cons on how I answered the question.\n\nMake sure you reference the job description to see whether I mentioned relavant skills, etc.\n\nUse the following format for the pros and cons list:  \n\nPros:\n- XYZ\n\nCons:\n- XYZ\n\nDo you understand?"},
		    {"role": "CHATBOT", "message": "Yes, I understand. Please give me the relevant details and I will only give you a pros and cons list along with a brief paragraph on advice."}
		  ],
		  connectors=[],
		  message=f"Here is the job description: {self.job_description}\n\nHere is the question: {self.question}\n\nHere is my response: {self.audio_transcript}.\n\nDo not say anything or ask me any questions after giving the final paragraph of advice!",
		)
		return "\n".join(response.text.split("\n")[:-1])





if __name__ == "__main__":
	response = "In a cybersecurity project, I, um, led the development of a threat detection system using, um, machine learning algorithms. Challenges included, like, refining the model for false positive reduction and, um, integrating it into existing security infrastructure. Through, um, iterative testing and, like, feedback, we achieved a high level of accuracy in, like, identifying potential threats. The success of the project highlighted my ability to lead, um, technical initiatives and, um, collaborate effectively within a team."
	job_description = "Required skills: Python, Java, SQL"
	question = "Tell me about a project you worked on. What were some challenges you faced?"
	x = CohereTool(response, job_description, question)
	print(x.get_sentiment_analysis())
	print(x.get_response_feedback())




